project:
  type: website

website:
  title: "Shayna Yang — Communicating with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Shayna-Yang
format:
  html:
    theme: flatly
    css: styles.css


